// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var getToday = (function() {
  let date = new Date();
  return new Date(date.getTime() - (date.getTimezoneOffset() * 60000))
    .toISOString()
    .split("T")[0];
});

function identifyCommand(cmd) {
  switch (cmd) {
    case "help" :
        return /* Help */0;
    case "ls" :
        return /* Ls */1;
    default:
      return /* Help */0;
  }
}

var CommandAndArguments = {
  identifyCommand: identifyCommand
};

function help(param) {
  console.log("Usage :-\n$ ./todo add \"todo item\"  # Add a new todo\n$ ./todo ls               # Show remaining todos\n$ ./todo del NUMBER       # Delete a todo\n$ ./todo done NUMBER      # Complete a todo\n$ ./todo help             # Show usage\n$ ./todo report           # Statistics");
  
}

function ls(param) {
  console.log("Need to work on it");
  
}

var Functions = {
  help: help,
  ls: ls
};

var cmd = Belt_Option.getWithDefault(Belt_Array.get(process.argv, 2), "help").trim();

var cmdArg = Belt_Array.get(process.argv, 3);

var cmd$1 = identifyCommand(cmd);

if (cmd$1) {
  console.log("Need to work on it");
} else {
  console.log("Usage :-\n$ ./todo add \"todo item\"  # Add a new todo\n$ ./todo ls               # Show remaining todos\n$ ./todo del NUMBER       # Delete a todo\n$ ./todo done NUMBER      # Complete a todo\n$ ./todo help             # Show usage\n$ ./todo report           # Statistics");
}

var todoPath = "./todo.txt";

var donePath = "./done.txt";

var encoding = "utf8";

exports.getToday = getToday;
exports.todoPath = todoPath;
exports.donePath = donePath;
exports.encoding = encoding;
exports.CommandAndArguments = CommandAndArguments;
exports.Functions = Functions;
exports.cmdArg = cmdArg;
exports.cmd = cmd$1;
/* cmd Not a pure module */
